// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcxmirnlnofaaidmvvdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjeG1pcm5sbm9mYWFpZG12dmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzNTU3MjUsImV4cCI6MjA3ODkzMTcyNX0.CMB_kgPFDL84knQKoaLXEq1kx-BEz-5YZeI2akCqa1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});